"""document doc_metadata

Revision ID: 779fd149f2c4
Revises: 8307313d50e6
Create Date: 2026-06-12 16:34:20.360869
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '779fd149f2c4'
down_revision: str | None = '8307313d50e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_metadata')
    # ### end Alembic commands ###
