"""document extracted_text and page_count

Revision ID: 8307313d50e6
Revises: fb181ea58796
Create Date: 2026-06-12 16:12:34.964293
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8307313d50e6'
down_revision: str | None = 'fb181ea58796'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
