"""workflow_instances and workflow_steps

Revision ID: 9efe1a3fd119
Revises: 19931b56224c
Create Date: 2026-06-12 17:32:55.345839
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9efe1a3fd119'
down_revision: str | None = '19931b56224c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_instance_id'), 'workflow_steps', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_instance_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_table('workflow_instances')
    # ### end Alembic commands ###
